feature: want to borrow list
mayu-snba19/hacku-vol4 pull request #82
Opened 2021-03-12 08:28 UTC by kazuki-komori

close #74

2021-03-12 08:59 UTC, TOMOFUMI-KONDO requested changes

2021-03-12 08:59 UTC, TOMOFUMI-KONDO commented on back/src/api/service/want_to_borrow.py
> +    def get_want_to_borrow_list(self) -> Tuple[dict, Any, Any]:
返り値dictではないですか？

2021-03-12 09:22 UTC, kazuki-komori commented on back/src/api/service/want_to_borrow.py
> +    def get_want_to_borrow_list(self) -> Tuple[dict, Any, Any]:
@TOMOFUMI-KONDO 

![image](https://user-images.githubusercontent.com/56425350/110919669-dc888b80-835f-11eb-8369-d7b438ff281b.png)

こうなるんですよね

2021-03-13 01:06 UTC, TOMOFUMI-KONDO approved these changes

2021-03-13 01:06 UTC, merged